### PR TITLE
The RFC process RFC

### PR DESCRIPTION
**Pull request by marijnh**
This RFC proposes an RFC process, both as a way to test-drive itself, and to provide space for feedback on the process.

[Rendered RFC](https://github.com/ProseMirror/rfcs/blob/rfcs/text/0000-rfc-process.md).

### CODE REVIEW

**Comment by ncphillips** [comment]
What would be the process for accepting an RFC? Would it be that there is one week for the community to voice their concerns, and then you @marijnh make the decision?

**Comment by marijnh** [comment]
Right now, the core team consists of me and @adrianheine. Hopefully we'll be able to extend that in the future.

**Comment by bradleyayers** [comment]
It'd be great to have some clarity around when a topic should be discussed in discuss.prosemirror.net or ProseMirror/rfcs. Intuitively I'd expect discussions to start on discuss, and then formalise into an RFC. One aspect I'm unsure about is exactly what that "migration" looks like. It's probably counter productive for the conversation to fork across the two platforms, so presumably a clear cutover (i.e. "this thread is locked, discussion to continue at ProseMirror/rfcs#0000").

**Comment by marijnh** [comment]
> It'd be great to have some clarity around when a topic should be discussed in discuss.prosemirror.net or ProseMirror/rfcs. Intuitively I'd expect discussions to start on discuss, and then formalise into an RFC

Yes, I think that's a good approach. An RFC can happen at the point where you have a clear enough idea of how something should work to write up a more or less formal description. Locking threads to funnel discussion towards a single place is probably a good idea. We can link back to the forum if we need to refer to something that was said there and is still relevant.

**Comment by ncphillips** [comment]
A bit more clarity over which topics should be put into an RFC would also be good.

For example, if I want to propose a new command for `prosemirror-commands` would that go in here, or should that just be an issue in that repository?

One of the challenges I faced when I first started learning Prosemirror was determining which packages were core and which were add-ons or even just example repositories.

**Comment by marijnh** [comment]
> A bit more clarity over which topics should be put into an RFC would also be good.

I find it hard to give a fast-and-hard rule for this. If something would benefit from review and discussion, an RFC is probably in place. The example with the new command would be such a case—committing to a new command, and designing it in such a way that we don't regret it later, probably requires some thought.

> One of the challenges I faced when I first started learning Prosemirror was determining which packages were core and which were add-ons or even just example repositories.

I should probably add a clear note about this to the readme files.

**Comment by Thinkscape** [comment]
Is the duration of a week a static concept?
Smaller feature requests might fit in that, but I can imagine an RFC of a new API or v1.0 release taking more than that to discuss or get enough eyeballs to consider well reviewed. 

Even the mother-of-all-RFCs has has just 2 people commenting on it (with number of views unknown as Github doesn't provide us with those stats).

What about improvements? If an RFC is of low detail or quality, will it be rejected right away (requiring opening a new one) or would the author get some time to work on it and address feedback?

**Comment by adrianheine** [comment]
One week is just the minimum time an RfC is open for discussion. I expect RfCs with actual discussion will almost always take longer.

**Comment by marijnh** [comment]
>  If an RFC is of low detail or quality, will it be rejected right away (requiring opening a new one) or would the author get some time to work on it and address feedback?

If it looks like it might be pulled around, the author will definitely get time and directions to improve it. With this kind of process, I do expect we'll occasionally get things that just seem so poorly conceptualized or in conflict with the vision for the project that we just reject them entirely so that no further time is wasted on it.

**Comment by marijnh** [comment]
I've merged this. Note that does not mean the process is now set in stone -- further changes may be proposed as new RFCs.

**Pull request merged**
